### ISSUE TITLE
[Bug]: Unable to log in on Android devices when using password manager autofill

### ISSUE THREAD

**Issue by yurividal** [henrygd/beszel#1011]
### Component

Hub

### Description

Beszel works fine on my computer. Any time I try to login on my phone, I get the login page, but pressing the login button does nothing. The page just sits there and never logs me in. I tried multiple browsers including Samsung internet browser and Brave.
Even setting to show desktop version doesn't help.
My beszel instance is behind nginx, by the way.

### Expected Behavior

I should be able to login

### Steps to Reproduce

Open https://beszel.mydomain.com on a mobile browser.
Try to login

### Category

Authentication

### Affected Metrics

Other

### OS / Architecture

Ubuntu 22.04

### Beszel version

Latest

### Installation method

Docker

### Configuration

```yaml

```

### Hub Logs

```json

```

### Agent Logs

```shell

```

**Comment by henrygd** [comment]
Is this for password login, oauth login, or both? Stock Android or spin off?

I can't reproduce on my Pixel 6a or BrowserStack.

**Comment by yurividal** [comment]
This is normal login, o Samsung OneUI.
I think the issue is actually on how beszel is being proxied by nginx proxy manager. If I open by IP and port of the container, it works.
Is there a specific nginx example or template for beszel?
I tried enabling web sockets, but that also didn't work.

**Comment by henrygd** [comment]
I'd recommend trying the nginx config in the PocketBase docs: https://pocketbase.io/docs/going-to-production/#using-reverse-proxy

```nginx
server {
    listen 80;
    server_name example.com;
    client_max_body_size 10M;

    location / {
        # check http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        proxy_read_timeout 360s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # enable if you are serving under a subpath location
        # rewrite /yourSubpath/(.*) /$1  break;

        proxy_pass http://127.0.0.1:8090;
    }
}
```

If you open your browser's devtools network tab or console do you see any errors after clicking the button?

**Comment by Tailscale-VPS** [comment]
@henrygd  It was working fine for months, but i don't know when it happenned maybe the recent update or the update before , because i was logged out today and same thing is happenning with me what's happenning with @yurividal . 
I am using traefik and there are no errors in proxy logs or browser network/console also its working everywhere else so i believe it's not a proxy issue.

**What i found**
Some time ago i started using code server (Vscode on web) and by using it everywhere i found something , it works everywhere except on android chrome (Crashes,shortcuts not working,etc), This led me in search of new browser but what i found is that it was not the issue of chrome it was the issue of chromium and as we all know except firefox all of android browsers are based on chromium, so all had the same issue.

Similarly i tested this thing with firefox android and its working without any issue,So this is the only current solution for me now to use firefox or any other browser if uare able to found which is not chromium based.

**Comment by sneak-it** [comment]
Chiming in to say same issue here - logging into PocketBase itself is no issue, however logging into the Beszel hub has me stuck on the login screen. Latest Chrome, android. Chrome on PC works no problem.

**Comment by abjoseph** [comment]
Experiencing the same issue with both **_chrome_** and **_brave_**, however **_edge_** is working fine, oddly enough.

**Beszel Version**: v12.6
**Android Version**: 16
**Phone Model**: Pixel 9a

**Comment by henrygd** [comment]
I haven't been able to reproduce on my Pixel 6a or on Browser Stack, so not sure what's going on here.

**Comment by sneak-it** [comment]
> I haven't been able to reproduce on my Pixel 6a or on Browser Stack, so not sure what's going on here.

Is there a way to get you some better logging @henrygd ? Not super familiar with what steps I could take to be more helpful other than 'login doesn't work'. Still a reproducible issue on 0.12.7.

**Comment by henrygd** [comment]
Is this only for oauth login? Maybe popup windows are blocked?

I tested on 5-6 different devices and both password and oauth worked for me first try.

You can check the logs page in PocketBase (`/_/#/logs`) for errors, maybe you'll get lucky.

**Comment by sneak-it** [comment]
This is for basic auth - email and password. Think I found something, set up USB debugging and got somewhere:

```
/assets/login-CLRBK-MU.js
{
    "typed": false,
    "success": false,
    "output": {
        "name": "my-password",
        "email": "username",
        "password": "my-password"
    },
    "issues": [
        {
            "kind": "schema",
            "type": "literal",
            "input": "my-password",
            "expected": "\"\"",
            "received": "\"my-password\"",
            "message": "Invalid type: Expected \"\" but received \"my-password\"",
            "path": [
                {
                    "type": "object",
                    "origin": "value",
                    "input": {
                        "email": "username",
                        "password": "my-password",
                        "name": "my-password"
                    },
                    "key": "name",
                    "value": "my-password"
                }
            ]
        }
    ]
}
```

Nothing relevant in pocketbase logs.

Seems the issue is the password. I created a brand new account with a different password and was able to login. I tried 'testings' and 'test-test' as passwords, those worked. This password causes the issue: `Systematic-Monitoring-33`

**Comment by henrygd** [comment]
Thanks! Looks like the error is being caused by Chrome automatically filling out a hidden honeypot field called `name`.

It has `autocomplete="off"` so I'm not sure why your password is being put there. I'll probably remove it since we have built-in rate limiting and browsers are unpredictable.

Edit: Maybe another app is filling it out? Password manager perhaps?

**Comment by shadybraden** [comment]
> Edit: Maybe another app is filling it out? Password manager perhaps?

Having the same issue using bitwarden to autofill

**Comment by Tailscale-VPS** [comment]
> > Edit: Maybe another app is filling it out? Password manager perhaps?
> 
> Having the same issue using bitwarden to autofill

+1
Tried copy pasting manually and it worked

**Comment by sneak-it** [comment]
> Thanks! Looks like the error is being caused by Chrome automatically filling out a hidden honeypot field called `name`.
> 
> It has `autocomplete="off"` so I'm not sure why your password is being put there. I'll probably remove it since we have built-in rate limiting and browsers are unpredictable.
> 
> Edit: Maybe another app is filling it out? Password manager perhaps?

Yes indeed, I utilize bitwarden as well.

**Comment by henrygd** [comment]
Okay, so the workaround for the time being is to copy/paste your email and password instead of allowing your password manager to autofill the hidden field.

I also use Bitwarden so I'll try to figure out if there's a solution besides removing the field.

**Comment by agustinusnathaniel** [comment]
> Okay, so the workaround for the time being is to copy/paste your email and password instead of allowing your password manager to autofill the hidden field.
> 
> I also use Bitwarden so I'll try to figure out if there's a solution besides removing the field.

Small note on the honeypot field in `LoginSchema`: it’s currently named `name`, which can be autofilled by password managers even when hidden. This may cause false positives and block real users.
https://github.com/henrygd/beszel/blob/main/internal/site/src/components/login/auth-form.tsx

Suggested fix: rename the field to a non-autofill name (eg company_website or hp_field) and disable `autocomplete` on the input. Honeypot works well, but relying on name is a bit risky for UX.

**Comment by henrygd** [comment]
@agustinusnathaniel Good idea, thanks! This has been updated for the next release, which should be out very soon.

**Comment by svenvg93** [comment]
@yurividal is the problem still present in the latest release?

**Comment by shadybraden** [comment]
@svenvg93 I for one am still having this issue on 0.18.2

**Comment by alepouna** [comment]
Interestingly on iOS (Using bitwarden, Safari, Chrome or Firefox) this is not replicatable. 
Still seeing this issue on Android though (Chrome/Brave) but not on Firefox. This might be a bug with the Bitwarden app it self and how it auto-fills field, might be worth bringing it up there.

**Comment by sneak-it** [comment]
Can confirm, issue still occurs on Android in 18.2.

**Comment by Nanganator** [comment]
The error generated why trying to log in with a password manager seems to be `The request requires valid record authorization token.`

```
{
  "id": "6z7rar9ttksr9ab",
  "created": "2026-01-28 22:13:32.691Z",
  "data": {
    "auth": "",
    "details": null,
    "error": "The request requires valid record authorization token.",
    "execTime": 0.01416,
    "method": "POST",
    "referer": "https://beszel.domain.com",
    "remoteIP": "123.456.789.123",
    "status": 401,
    "type": "request",
    "url": "/api/collections/users/auth-refresh",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "userIP": "123.456.789.123"
  },
  "message": "POST /api/collections/users/auth-refresh",
  "level": 8
}
```


EDIT: Ok maybe not. This error is thrown every time the login page is loaded.

Been working around it by just copy and pasting my username and password into the logon page from my Password Manager.

**Comment by henrygd** [comment]
Found this extremely helpful article by @alexis- and implemented the suggested fixes in https://github.com/henrygd/beszel/commit/6723ec8ea401d6ce80061c0aab2b2817cb73c52d

https://dev.to/alexisfranorge/why-your-honeypot-catches-humans-not-bots-3bcd

Fingers crossed this will finally be fixed in the next release 👍

**Comment by agustinusnathaniel** [comment]
TIL on these `data-*` attribute specific for each password manager
Nice founding and hoping it worked 

> Found this extremely helpful article by [@alexis-](https://github.com/alexis-) and implemented the suggested fixes in [6723ec8](https://github.com/henrygd/beszel/commit/6723ec8ea401d6ce80061c0aab2b2817cb73c52d)
> 
> https://dev.to/alexisfranorge/why-your-honeypot-catches-humans-not-bots-3bcd
> 
> Fingers crossed this will finally be fixed in the next release 👍

**Comment by agustinusnathaniel** [comment]
Issue Still reproducible on Android with latest Beszel version

[In bitwarden case] I think those `data-` attribute only applies for desktop web/browser bitwarden client, as I looked onto bitwarden android source code it doesn't have `data-bwignore` related exception, only found on the web based client app

**Comment by pvanderlinden** [comment]
I have the same issue, bitwarden with chrome (Firefox works fine), the password manager fills the hidden field "website" with the password.

**Comment by MoKhajavi75** [comment]
Same here on Android, latest Chrome and latest Bitwarden

**Comment by Damilola-GZY** [comment]
I have fixed the issue and opened a pull request. Awaiting review.

**Comment by scr4bble** [comment]
> I have fixed the issue and opened a pull request. Awaiting review.  

I am not a maintainer or anything but quickly checking the PR. It's really messy :/ hard to see your changes with so much updated formatting. I believe you should clean it out before expecting a review. (just my thoughts, hope they don't land badly)

**Comment by scr4bble** [comment]
@henrygd any chance you could look at this issue? It's still happening on my android Brave browser with Bitwarden. I never had such issue with any other website...

**Comment by Damilola-GZY** [comment]
> > I have fixed the issue and opened a pull request. Awaiting review.
> 
> I am not a maintainer or anything but quickly checking the PR. It's really messy :/ hard to see your changes with so much updated formatting. I believe you should clean it out before expecting a review. (just my thoughts, hope they don't land badly)

Thanks for the feedback, I just reformatted it.
Care to review it with me?
Any help is appreciated.

**Comment by scr4bble** [comment]
Sure thing, but I don't see the PR so I guess you will need to link it here.

**Comment by svenvg93** [comment]
Please check with the latest `0.18.8` release.

**Comment by ShlomiD83** [comment]
> Please check with the latest `0.18.8` release.

Works perfectly now.

**Comment by scr4bble** [comment]
Same for me. Issue seems to be fixed. Thanks a lot.

**Comment by Damilola-GZY** [comment]
Same here. Thanks a lot. Amazing work done 👌🏿
