### ISSUE TITLE
[Bug]: Unable to run version 0.15 on laptop if battery is not detected

### ISSUE THREAD

**Issue by GreyChame1eon** [henrygd/beszel#1353]
### Component

Agent

### Description

Thanks for your project, it awesome!

I have a small setup with few agents, some of them Windows-based. Prior version 0.15 everything was fine, but versions 0.15 and 0.15.2 cannot run on one of the my computers

Here are the details:
- ancient Sony Vaio laptop with i7-3632QM and HM77 chipset
- Windows 11 Pro
- Agent was previously installed from binary with NSSM

Version 0.14.1 (and previous) is good, but when I try to run 0.15 or 0.15.2 versions, I've got an error:

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x7ff68b3a490d]

goroutine 1 [running]:
github.com/henrygd/beszel/agent/battery.HasReadableBattery()
	/home/runner/work/beszel/beszel/agent/battery/battery.go:24 +0x4d
github.com/henrygd/beszel/agent/battery.GetBatteryStats()
	/home/runner/work/beszel/beszel/agent/battery/battery.go:38 +0x17
github.com/henrygd/beszel/agent.(*Agent).getSystemStats(_, _)
	/home/runner/work/beszel/beszel/agent/system.go:81 +0x78
github.com/henrygd/beszel/agent.(*Agent).gatherStats(0xc0000ca340, 0x0)
	/home/runner/work/beszel/beszel/agent/agent.go:143 +0xdd
github.com/henrygd/beszel/agent.NewAgent({0x0, 0x0, 0x0})
	/home/runner/work/beszel/beszel/agent/agent.go:117 +0x7f0
main.main()
	/home/runner/work/beszel/beszel/internal/cmd/agent/agent.go:149 +0x129
```

I've tried to run exe with or without "LHM=true" setting with no luck.

0.14.1 version just show the warning and continue to work:

```text
No battery found err="Could not retrieve battery info: `A device which does not exist was specified.`"
```

I completely understand that there is no point to support ancient hardware and add detection of the battery (BTW  it installed and work well), but is it possible to avoid process crashing as earlier?

### Expected Behavior

Skip the crash, just write log and continue

### Steps to Reproduce

1. Proper install agent 0.14.1
2. Stop the service, replace the exe to 0.15.2, run the service and got the error

### Category

Installation

### Affected Metrics

Other

### OS / Architecture

windows/amd64

### Beszel version

0.15.2

### Installation method

Binary

### Configuration

```yaml
KEY=<edited>
TOKEN=<edited>
HUB_URL=https://<edited>
LISTEN=45876
EXTRA_FILESYSTEMS=D:__Data-Disk
LHM=true
PRIMARY_SENSOR=CPU Package
```

### Hub Logs

```json

```

### Agent Logs

```shell
2025/10/30 16:23:38 INFO Data directory path=C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\beszel-agent
2025/10/30 16:23:38 DEBUG 0.15.2
2025/10/30 16:23:38 DEBUG Not monitoring ZFS ARC err="open /proc/spl/kstat/zfs/arcstats: The system cannot find the path specified."
2025/10/30 16:23:38 DEBUG Disk partitions="[{\"device\":\"C:\",\"mountpoint\":\"C:\",\"fstype\":\"NTFS\",\"opts\":[\"rw\",\"compress\"]} {\"device\":\"D:\",\"mountpoint\":\"D:\",\"fstype\":\"NTFS\",\"opts\":[\"rw\",\"compress\"]}]"
2025/10/30 16:23:38 DEBUG Disk I/O diskstats="map[C::{\"readCount\":10711276,\"mergedReadCount\":0,\"writeCount\":61033009,\"mergedWriteCount\":0,\"readBytes\":415767736832,\"writeBytes\":3367466717184,\"readTime\":65243,\"writeTime\":905222,\"iopsInProgress\":0,\"ioTime\":0,\"weightedIO\":0,\"name\":\"C:\",\"serialNumber\":\"\",\"label\":\"\"} D::{\"readCount\":10153,\"mergedReadCount\":0,\"writeCount\":48,\"mergedWriteCount\":0,\"readBytes\":337849344,\"writeBytes\":196608,\"readTime\":118,\"writeTime\":4,\"iopsInProgress\":0,\"ioTime\":0,\"weightedIO\":0,\"name\":\"D:\",\"serialNumber\":\"\",\"label\":\"\"}]"
2025/10/30 16:23:38 INFO Root disk mountpoint=/ io=C:
2025/10/30 16:23:39 INFO Detected network interface name="Wi-Fi 2" sent=1105753836 recv=3957709360
2025/10/30 16:23:39 DEBUG Failed to get Docker version; retrying attempt=1 error="Get \"http://localhost/version\": dial unix /var/run/docker.sock: connect: A socket operation encountered a dead network."
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x7ff68b3a490d]

goroutine 1 [running]:
github.com/henrygd/beszel/agent/battery.HasReadableBattery()
	/home/runner/work/beszel/beszel/agent/battery/battery.go:24 +0x4d
github.com/henrygd/beszel/agent/battery.GetBatteryStats()
	/home/runner/work/beszel/beszel/agent/battery/battery.go:38 +0x17
github.com/henrygd/beszel/agent.(*Agent).getSystemStats(_, _)
	/home/runner/work/beszel/beszel/agent/system.go:81 +0x78
github.com/henrygd/beszel/agent.(*Agent).gatherStats(0xc0000ca340, 0x0)
	/home/runner/work/beszel/beszel/agent/agent.go:143 +0xdd
github.com/henrygd/beszel/agent.NewAgent({0x0, 0x0, 0x0})
	/home/runner/work/beszel/beszel/agent/agent.go:117 +0x7f0
main.main()
	/home/runner/work/beszel/beszel/internal/cmd/agent/agent.go:149 +0x129
2025/10/30 16:23:41 INFO Data directory path=C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\beszel-agent
2025/10/30 16:23:41 DEBUG 0.15.2
```

**Comment by henrygd** [comment]
Thanks, I didn't realize nil was possible there. Should be fixed in the next release.

**Comment by henrygd** [comment]
Let me know if this is fixed in 0.15.3 👍

**Comment by GreyChame1eon** [comment]
> Let me know if this is fixed in 0.15.3 👍

Sorry to upset you, but the problem remains. I've tried 0.15.3 and 0.15.4

```text
2025/11/05 16:37:41 INFO Data directory path=C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\beszel-agent
2025/11/05 16:37:42 DEBUG 0.15.3
2025/11/05 16:37:42 DEBUG Not monitoring ZFS ARC err="open /proc/spl/kstat/zfs/arcstats: The system cannot find the path specified."
2025/11/05 16:37:42 DEBUG Disk partitions="[{\"device\":\"C:\",\"mountpoint\":\"C:\",\"fstype\":\"NTFS\",\"opts\":[\"rw\",\"compress\"]} {\"device\":\"D:\\\\\",\"mountpoint\":\"D:\\\\\",\"fstype\":\"NTFS\",\"opts\":[\"rw\",\"compress\"]}]"
2025/11/05 16:37:42 DEBUG Disk I/O diskstats="map[C::{\"readCount\":11275658,\"mergedReadCount\":0,\"writeCount\":65075358,\"mergedWriteCount\":0,\"readBytes\":440545354240,\"writeBytes\":3449666766848,\"readTime\":68513,\"writeTime\":936843,\"iopsInProgress\":0,\"ioTime\":0,\"weightedIO\":0,\"name\":\"C:\",\"serialNumber\":\"\",\"label\":\"\"} D::{\"readCount\":10234,\"mergedReadCount\":0,\"writeCount\":56,\"mergedWriteCount\":0,\"readBytes\":339540992,\"writeBytes\":229376,\"readTime\":133,\"writeTime\":6,\"iopsInProgress\":0,\"ioTime\":0,\"weightedIO\":0,\"name\":\"D:\",\"serialNumber\":\"\",\"label\":\"\"}]"
2025/11/05 16:37:43 INFO Root disk mountpoint=/ io=C:
2025/11/05 16:37:43 INFO Detected network interface name="Wi-Fi 2" sent=1657885858 recv=5434865399
2025/11/05 16:37:43 DEBUG Failed to get Docker version; retrying attempt=1 error="Get \"http://localhost/version\": dial unix /var/run/docker.sock: connect: A socket operation encountered a dead network."
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff7e96d522e]

goroutine 1 [running]:
github.com/henrygd/beszel/agent/battery.GetBatteryStats()
	/home/runner/work/beszel/beszel/agent/battery/battery.go:77 +0x14e
github.com/henrygd/beszel/agent.(*Agent).getSystemStats(_, _)
	/home/runner/work/beszel/beszel/agent/system.go:81 +0x78
github.com/henrygd/beszel/agent.(*Agent).gatherStats(0xc0000d0340, 0x0)
	/home/runner/work/beszel/beszel/agent/agent.go:143 +0xdd
github.com/henrygd/beszel/agent.NewAgent({0x0, 0x0, 0x0})
	/home/runner/work/beszel/beszel/agent/agent.go:117 +0x7f0
main.main()
	/home/runner/work/beszel/beszel/internal/cmd/agent/agent.go:149 +0x129
2025/11/05 16:37:44 INFO Data directory path=C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\beszel-agent
2025/11/05 16:37:44 DEBUG 0.15.3
```

```text
2025/11/05 16:35:35 INFO Data directory path=C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\beszel-agent
2025/11/05 16:35:35 DEBUG 0.15.4
2025/11/05 16:35:35 DEBUG Not monitoring ZFS ARC err="open /proc/spl/kstat/zfs/arcstats: The system cannot find the path specified."
2025/11/05 16:35:35 DEBUG Disk partitions="[{\"device\":\"C:\",\"mountpoint\":\"C:\",\"fstype\":\"NTFS\",\"opts\":[\"rw\",\"compress\"]} {\"device\":\"D:\\\\\",\"mountpoint\":\"D:\\\\\",\"fstype\":\"NTFS\",\"opts\":[\"rw\",\"compress\"]}]"
2025/11/05 16:35:35 DEBUG Disk I/O diskstats="map[C::{\"readCount\":11275426,\"mergedReadCount\":0,\"writeCount\":65073761,\"mergedWriteCount\":0,\"readBytes\":440539116032,\"writeBytes\":3449612347904,\"readTime\":68489,\"writeTime\":936815,\"iopsInProgress\":0,\"ioTime\":0,\"weightedIO\":0,\"name\":\"C:\",\"serialNumber\":\"\",\"label\":\"\"} D::{\"readCount\":10234,\"mergedReadCount\":0,\"writeCount\":56,\"mergedWriteCount\":0,\"readBytes\":339540992,\"writeBytes\":229376,\"readTime\":133,\"writeTime\":6,\"iopsInProgress\":0,\"ioTime\":0,\"weightedIO\":0,\"name\":\"D:\",\"serialNumber\":\"\",\"label\":\"\"}]"
2025/11/05 16:35:35 INFO Root disk mountpoint=/ io=C:
2025/11/05 16:35:35 INFO Detected network interface name="Wi-Fi 2" sent=1655875304 recv=5430175060
2025/11/05 16:35:35 DEBUG Failed to get Docker version; retrying attempt=1 error="Get \"http://localhost/version\": dial unix /var/run/docker.sock: connect: A socket operation encountered a dead network."
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff7bd21522e]

goroutine 1 [running]:
github.com/henrygd/beszel/agent/battery.GetBatteryStats()
	/home/runner/work/beszel/beszel/agent/battery/battery.go:77 +0x14e
github.com/henrygd/beszel/agent.(*Agent).getSystemStats(_, _)
	/home/runner/work/beszel/beszel/agent/system.go:81 +0x78
github.com/henrygd/beszel/agent.(*Agent).gatherStats(0xc00012e1a0, 0x0)
	/home/runner/work/beszel/beszel/agent/agent.go:143 +0xdd
github.com/henrygd/beszel/agent.NewAgent({0x0, 0x0, 0x0})
	/home/runner/work/beszel/beszel/agent/agent.go:117 +0x7f0
main.main()
	/home/runner/work/beszel/beszel/internal/cmd/agent/agent.go:149 +0x129
2025/11/05 16:35:38 INFO Data directory path=C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\beszel-agent
2025/11/05 16:35:38 DEBUG 0.15.4
```

**Comment by henrygd** [comment]
Thank you, I've made further updates here and it should be fixed in 0.16.0. Let me know whenever you can try it 👍

**Comment by GreyChame1eon** [comment]
It if fine now!
Thank you very much!!!

**Comment by henrygd** [comment]
No problem, thanks for reporting!
