### ISSUE TITLE
Windows Agent not reporting CPU usage properly

### ISSUE THREAD

**Issue by d31tcjg** [henrygd/beszel#434]
Here is what Beszel is reporting 

![Image](https://github.com/user-attachments/assets/3abfd8af-b04a-4c84-99b6-650923cfdab3)

What is actually on the system:

![Image](https://github.com/user-attachments/assets/b530755e-a767-479b-86f3-8520bcb7c46d)

**Comment by henrygd** [comment]
Thanks for letting me know. Will look into this asap and try to get it fixed in the next release.

**Comment by VampDev** [comment]
Can confirm this is still happening - windows server 2025 datacenter standard

Task Manager reporting CPU is almost maxed and the beszel hub is only reporting 6% CPU usage

**Comment by henrygd** [comment]
Thanks, I have other Windows tasks coming up shortly so I'll take a look at this again.

Do you have an Intel CPU? And is Beszel displaying your CPU model / core count correctly?

**Comment by VampDev** [comment]
> Thanks, I have other Windows tasks coming up shortly so I'll take a look at this again.
> 
> Do you have an Intel CPU? And is Beszel displaying your CPU model / core count correctly?

I've got a Intel i7-9750H in the node and the Model/Core count is correct

<img width="1407" height="1053" alt="Image" src="https://github.com/user-attachments/assets/829cae90-e5be-4983-b7e8-b803a926537b" />

**Comment by svenvg93** [comment]
No activity on this issue for a long time. Closing it for now. If the issue persists or becomes relevant again, feel free to open a new issue or discussion.
